### ISSUE TITLE
In vitro versus in vivo evidence

### ISSUE THREAD

**Issue by samuelrosko** [dbmi-pitt/DIKB-Micropublication#16]
As far as I know, we have not included any in vitro data in our import of the old DIKB to the MP/OA/NP system... However, we probably need a way to distinguish between the types for purposes of developing queries... We were considering adding in vivo/in vitro as subclasses of representation? ie in vitro materials/methods/data

**Comment by jodischneider** [comment]
Sam will write in vitro evidence with a 'like' matching SPARQL query -- for EV_EX_Met_Enz_ID and EV_EX_Met_Enz_Inhibit and their subclasses.

In the future we will want to formalize the evidence taxonomy. We envision that:
- MP:Material will have subclasses for in vivo and in vitro
- The evidence taxonomy <http://dbmi-icode-01.dbmi.pitt.edu/dikb-evidence/just-inclusion-criteria/just-inclusion-criteria.html> will be used to create MP:Material subclasses (subclassing the in vivo class or in vitro class as appropriate)
(and at that point we will revisit the query)

**Comment by jodischneider** [comment]
What resolution did we come to with this? Did we take some action? Decide
not to do anything?

**Comment by samuelrosko** [comment]
Sorry, I misunderstood what this issue was about. Not resolved yet.

**Comment by jodischneider** [comment]
Subclass Method with "in vitro Method" and "in viva Method".

All other Methods should be subclasses of one or the other of those.

**Comment by jodischneider** [comment]
Queries to updated.
