### ISSUE TITLE
resolve terminology: 'assertion' vs. 'claim'

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#18]
In descriptions of our queries (and their filenames), we refer to MP:Claim as 'assertion'; originally this was to distinguish from (insurance) claim.

Should we choose new terminology now that we are adding NP:Assertion's?
In the paper we strongly distinguish between 'assertion' (computable/NP:Assertion) and 'claim' (textual/MP:Claim).

**Comment by samuelrosko** [comment]
We've shifted to using claim to refer to mp:Claims
