### ISSUE TITLE
Revisit information needs of "act as support or rebuttal"

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#22]
We have rephrased use cases that mention rebuttal. We will need to check that we are still meeting information needs appropriately.

e.g. "Which single evidence items act as support or rebuttal for multiple assertions" -->
"Which single evidence items are the unique challenge for multiple assertions"

**Comment by samuelrosko** [comment]
That example has the correct interpretation of rebuttal... queries where rebuttal refers to rejected evidence and where it refers to "challenges" have been dealt with
