### ISSUE TITLE
add mp:Reference

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#26]
Add mp:Reference. This should be the OA:hasSource associated with the target of the OA that points to the mp:Data, mp:Material, mp:Methods.

**Comment by jodischneider** [comment]
mp:Reference, as used in the original paper, is the backing for a claim NOT DISCUSSED in the paper. See Figure 7 page 15 and Figure 8 page 16 of http://www.biomedcentral.com/content/pdf/2041-1480-5-28.pdf

The use case in the paper is mainly digital abstracts -- so that 
MP1 mp:represents  Attribution1

Ways to resolve this:

(a) add mp:represents pointing to an identifier for the paper [this is appropriate if there is only one main paper providing supporting evidence (as opposed to Reference backing) for an MP]

(b) if MP is going to discuss evidence from multiple sources, mp:represents is misleading. Should we mint another relationship? Clarify the scope of mp:represents?

**Comment by timclark** [comment]
In the example on p15 (fig 7) mp:Reference to Harrison et al. was provided by Spilman et al in support of their claim, made in the paper, that Rapamycin inhibits the mTOR pathway.  

The overall claim they are making has three components from a logical point of view, each of which they assert and provide backing references for:

1 - Rapamycin inhibits mTOR pathway 
2 - PDAPP J20 transgenics are a (“good” implied here but they go with “popular") mouse model of Alzheimer disease 
3 - Feeding Rapamycin to these mice reverses AD symptomatology and pathology

So I’m not quite sure what your comment means, but maybe a skype would clarify? 

Tim

**Comment by jodischneider** [comment]
Right. mp:Reference is used for the backing references. But for the original Spilman et al paper you don't use mp:Reference (because it's not referring to itself). This makes sense for a digital abstract -- the MP mp:represents the Spilman et al paper.

In our case, the MP is not specifically intended to be a digital abstract of the document (paper/drug label/...). (It happens to do this to a certain extent.) The main goal, though, is for the MP to represent the claim and all its supporting evidence--which may come from multiple papers that don't a priori cite each other.

So it's not clear that our MP "mp:represents" the paper (it doesn't fully represent it; and there might not be a 1-1 relationship between the MP and the document).

Does that make sense, Tim? If not, let's try to talk later this week.

**Comment by timclark** [comment]
Not clear to me so let’s talk - I get the distinction in use cases but not your approach

**Comment by jodischneider** [comment]
Yifan will implement using the PMID URLs associated with the implementation: <http://dx.doi.org/10.1016/S0009-9236(98)90151-5> 
  mp:supports :C1 ;
  rdf:type mp:Reference .
