### ISSUE TITLE
Express dates in ISO 8601

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#3]
Dates should be expressed in ISO 8601 (or an approximation thereof). So for instance
"07/02/2007 17:30:07\n" should be
"2007-07-02 17:30:07Z" (assuming UTC timezone). 

Otherwise this could be read as February 7th or July 2nd.
See e.g. https://en.wikipedia.org/wiki/ISO_8601

**Comment by samuelrosko** [comment]
That's the format I used for my NP provenance/pubInfo times... the issue with the times in the MP model is that they are pulled as strings from the DIKB, so I'll look into a way to convert them

**Comment by samuelrosko** [comment]
I updated all of the times in the MP graph by using string matching in Yifan's script. I will show him what I did tomorrow and upload the changes then.
