### ISSUE TITLE
Query review : use the evidence type at the Method not the Data

### ISSUE THREAD

**Issue by ningyifan** [dbmi-pitt/DIKB-Micropublication#37]
This is because there are actual definition in an owl ontology for the evidence types attached to MP:Method but there is nothing for the evidence types attached to MP:Data (yet)

**Comment by samuelrosko** [comment]
This is difficult for me to do, because for say, the distribution of evidence types -- STAT04-06, we want to include drug label statements. if I go down to the method level, the drug label statements will be excluded.

**Comment by samuelrosko** [comment]
Temporary fix is to separate into two counts - one for claims, one for the rest of evidence types...

This is a limitation of the model that has to be addressed in the future...

Perhaps somehow tag the type in the OA?

**Comment by jodischneider** [comment]
Brainstorming:

-- In some cases, drug labels report methods. In this case could we use the
Method taxonomy?
-- Otherwise, would it make sense to label the Method as "unknown --
untraceable drug label".

This might be a hack -- and we might not want to imply that there was a
method, in case the method is in fact unknown/possibly non-existent.

**Comment by jodischneider** [comment]
This hides 2 issues that precede it

1. How do we handle non-traceable drug labels?
2. Do we want to make an ontology for data types.

**Comment by jodischneider** [comment]
1. How do we handle non-traceable drug labels?
Cite non-traceable drug labels as mp:Reference. Include label, data, setID, version. Develop template.

2. Yes, we want to make an ontology for data types.

**Comment by jodischneider** [comment]
Queries still need to be updated.
