### ISSUE TITLE
Add MP:Argues

### ISSUE THREAD

**Issue by rkboyce** [dbmi-pitt/DIKB-Micropublication#38]
See Fig 2 of the manuscript - right now I don't think there is a URL for a resource pointing to a  claim with MP:Argues - these need to be added to graph.

**Comment by rkboyce** [comment]
Also, the current implementation has MP:Data directly support MP:Claim instead of, as in the figure, supporting a study that supports the claim.

**Comment by jodischneider** [comment]
2 issues here.

For 1st half: TODO: add e.g. MP1 mp:argues C1. (We may want provenance for MP1 etc later).

For 2nd half, WONTFIX: Study does not seem to be needed -- plan is to remove that from the figure (wish we'd noticed earlier).

**Comment by samuelrosko** [comment]
Yifan implemented this at roughly 4PM on 2015-07-29.
