### ISSUE TITLE
Update rdf:datatype of OA annotations, should be a URI, not a string

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#41]
Update rdf:datatype of OA annotations, should be a URI, not a string.

Example of current (wrong) approach:
<oa:hasSource rdf:datatype="&xsd;String">http://www.ncbi.nlm.nih.gov/pubmed/9728898</oa:hasSource>

**Comment by samuelrosko** [comment]
Fixed this issue, was a one line code change... will push update later today.
