### ISSUE TITLE
problems with rdf:subClassOf mp:Data/mp:Method

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#43]
I'd expect Data and Method to be disjoint. So I'd expect e.g. #EV_CT_PK_Phenotype_Data and #EV_CT_PK_Phenotype_Method here, rather than:

    <owl:Class rdf:about="http://dbmi-icode-01.dbmi.pitt.edu/dikb-evidence/DIKB_evidence_ontology_v1.3.owl#EV_CT_PK_Phenotype">
        <rdfs:subClassOf rdf:resource="&mp;Data"/>
        <rdfs:subClassOf rdf:resource="&mp;Method"/>
    </owl:Class>

Similarly this looks wrong:

    

    <owl:Class rdf:about="http://dbmi-icode-01.dbmi.pitt.edu/dikb-evidence/DIKB_evidence_ontology_v1.3.owl#EV_CT_Pharmacokinetic">
        <rdfs:subClassOf rdf:resource="&mp;Data"/>
        <rdfs:subClassOf rdf:resource="&mp;Method"/>
    </owl:Class>
    

    

    <owl:Class rdf:about="http://dbmi-icode-01.dbmi.pitt.edu/dikb-evidence/DIKB_evidence_ontology_v1.3.owl#EV_CT_Pharmacokinetic_Data"/>
    

    

    <owl:Class rdf:about="http://dbmi-icode-01.dbmi.pitt.edu/dikb-evidence/DIKB_evidence_ontology_v1.3.owl#EV_CT_Pharmacokinetic_Material">
        <rdfs:subClassOf rdf:resource="&mp;Material"/>
    </owl:Class>
    
I'd expect #EV_CT_Pharmacokinetic_Data to be a subClassOf mp:Data

**Comment by jodischneider** [comment]
For 1st problem:
Need to update OWL from http://dbmi-icode-01.dbmi.pitt.edu/dikb-evidence/just-inclusion-criteria/just-inclusion-criteria.html

**Comment by jodischneider** [comment]
mp:Data part of the problem resolved with edit to https://github.com/dbmi-pitt/DIKB-Micropublication/blob/master/scripts/mp-scripts/dikbv1.2-to-MP-plus-OA.py

**Comment by rkboyce** [comment]
I created a web protege project and invited you all so we can begin to define the methods and data types. It seems the instances will all will be related by MP:Supports but I will need to add discussion of how the classes are related to  the WG Standard Dev discussions

**Comment by jodischneider** [comment]
Next steps: added "Discuss data and materials taxonomy" to WG Standard Dev agenda 
Current draft:
https://github.com/dbmi-pitt/DIKB-Evidence-analytics/blob/master/dikb-ontology/dikb-revision-ontologies-owl-REVISION-50/DIKB_evidence_ontology_sam_update.owl
