### ISSUE TITLE
Source statements (needs manual correction)

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#8]
Source statements probably need manual correction. This is expected anytime the quote is not found in the abstract (frequently true for methods statements).

Example:
<urn:uuid:0dcd197a-9a74-40c8-8bd3-6d89e8529437> <http://www.w3.org/ns/oa#hasSource> "" .

**Comment by samuelrosko** [comment]
I know this was a year ago, but can you explain this? I don't quite understand this issue

**Comment by jodischneider** [comment]
TODO:
10 items without source (based on FA-01). 
Grab info from old DIKB and add into CSV for import.

**Comment by samuelrosko** [comment]
The CSV has been manually updated to include this missing information. See the "Quality Assurance" issue for more details.
