### ISSUE TITLE
Is a string expected for oa:annotatedBy?

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#9]
Is a string expected for oa:annotatedBy? Check what the plugins we use will output.

**Comment by samuelrosko** [comment]
oa:annotatedBy and prov:wasAttributedTo both have the domain of "entity" and range of "agent"

As far as I can tell, agent can be either a STRING or a URI, though a URI seems far more useful...

Should we switch the target of "oa:annotatedBy" in the MP graphs to the same URI I used in my full-nanopubs?

**Comment by jodischneider** [comment]
TODO: Use URI. For Rich, use the same ORCID URI.

**Comment by samuelrosko** [comment]
I added string matching to use Dr. Boyce's ORCID rather than boycer. Will upload changes tomorrow.
